# Font
font-name=Nercone Mono CJK Variable
font-size=12

# Palette
palette=custom

palette-black=0,0,0
palette-dark-grey=64,64,64
palette-light-grey=191,191,191
palette-white=255,255,255

palette-red=191,57,57
palette-green=0,191,96
palette-yellow=191,159,0
palette-blue=57,124,191
palette-magenta=134,77,191
palette-cyan=77,153,191

palette-light-red=255,77,77
palette-light-green=0,255,128
palette-light-yellow=255,213,0
palette-light-blue=77,166,255
palette-light-magenta=179,102,255
palette-light-cyan=102,204,255
